POST http://localhost:5000/api/user/register
Content-Type: application/json

{
    "firstName": "abiola",
    "surname": "olaide",
    "email": "olaideab@gmail.com",
    "phone":    "09038997696",
    "password": "olaide2",
    "referral": "#gtjdje"
}